use_frameworks!

platform :ios, '9.0'

target 'BolanKit_Example' do
  pod 'BolanKit', :path => '../'

  target 'BolanKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
